import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/global/main-header";
import MainFooter from "@/components/global/main-footer";

const font = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <MainHeader />
          {children}
          <MainFooter />
        </main>
      </body>
    </html>
  );
}
